#!/bin/bash

function listColors() {
	num=1;
	for n in {1..254}
	do
		tput setaf $n # set foreground color
		case $num in
			1)
			printf "   --<||><| %3d |>" "$n"; # begining of line
			;;
			10 )
			printf "<| %3d |><||>--\n\r" "$n"; # end of line
			num=0; # reset number for next line, increments at bottom of case statment
			;;
			*)
			printf "<| %3d |>" "$n"; # middle of line
			;;
		esac
		tput sgr0 # reset foreground color

	:   $((num++))
	    sleep 0.005
	done;
	echo -ne "\n\r";
}

function listEscapeCodes() {

	echo "PALETTE OF 8 COLORS (bold, high intensity, normal, faint)"
	for i in {30..37}; do printf "\e[1;${i}m1;%-2s\t" "$i"; done; echo
	for i in {90..97}; do printf "\e[${i}m%+4s\t" "$i"; done; echo
	for i in {30..37}; do printf "\e[${i}m%+4s\t" "$i"; done; echo
	for i in {30..37}; do printf "\e[2;${i}m2;%-2s\t" "$i"; done;

	echo "\n\n\nPALETTE OF 256 COLORS (only normal)"
	local j=8
	for i in {0..255}; do
	    [[ $i = 16 ]] && j=6
	    [[ $i = 232 ]] && j=8
	    printf "\e[38;5;${i}m38;5;%-4s" "${i}"
		sleep 0.005
	    (( i>15 && i<232 )) && printf "\e[52C\e[1;38;5;${i}m1;38;5;%-4s\e[52C\e[2;38;5;${i}m2;38;5;%-4s\e[126D" "${i}" "${i}"

	    [[ $(( $(( $i - 15 )) % $j )) = 0 ]] && echo
	    [[ $(( $(( $i - 15 )) % $(( $j * 6 )) )) = 0 ]] && echo

	done;
}

case $1 in
	"e")
		listEscapeCodes;
	;;

	"all")
		listColors;
		listEscapeCodes;
	;;

	*)
		listColors;
	;;
esac
