#!/bin/bash

# Prints env as name:value list
function listEnvVars(){
	local _num=0 ## Line numbers.
    printf "\n\r"
    printf " \e[1;37mNo\t  %24s %-56s \n\r" $'\e[1;37mKEY ' $'   \e[1;37mVALUE'
	printenv | while read -r _val
	do
	:	$((++_num));
        [[ $((_num % 2)) -eq 0 ]] && tput setaf 4 || tput setaf 14
        _key=${_val//=*}
        _value=${_val//*=}
        if [[ "$_key" =~ PATH ]]
        then
            continue;
        else
            printf " %2d %24s | %-56s \n\r" "$_num" "$_key" "$_value"
        fi
	done
    tput sgr0;
}

listEnvVars;
unset -f listEnvVars;
exit 0;
