#!/bin/bash

# Prints env as name:value list
function printEnvVars(){
	local _num=0 ## Line numbers.
    printf "\n\r"
    printf "%-6s%24s%-56s\n\r" "${hdr}No.${rst}" "${hdr}Key${rst}" "${hdr}Value${rst}"
	printenv | while read -r _val
	do
	:	$((++_num));
        [[ $((_num % 2)) -eq 0 ]] && tput setaf 4 || tput setaf 14
        _key=${_val//=*}
        _value=${_val//*=}
        if [[ "$_key" =~ PATH ]]
        then
            continue;
        else
            printf " %2d %24s | %-56s \n\r" "$_num" "$_key" "$_value"
        fi
	done
    tput sgr0;
}

# for i in $(printenv); do; echo -e "$i"; done; 

function listEnvVars() {
	local num=1;
    printf "${hdr}%-6s${hdr}%-36s\t    ${hdr}%-56s \n\r" "No.${lu}    " "Key${lu}" "Value${rst}"
    for item in $(printenv)
    do
    	[[ "$item" =~ PATH ]] && continue
    	printf "${wht}%-6s ${grn}%-36s ${ylw}%-56s$rst \n\r" "$num." "${item//=*}" "${item//*=}";
:		$((++num));
	done
    	printf "${wht}%-6s ${grn}%-36s ${ylw}%-56s$rst \n\r" "$num." "PATH" "$(echo $PATH)";
}

listEnvVars;
unset -f listEnvVars;
exit 0;
