#!/bin/bash

function listUsers() {

    # local dbSwitch=$2;
    local num=0;

    for u in $(dscl . list /Users | grep -v '^_')
    do
    :   $((++num));
        printf "$blu%6d.\t$wht%-64s$rst\n\r" "$num" "$u";
    done;
}

listUsers;
unset -f listUsers;
exit 0;
